# Generated by Django 3.2.9 on 2021-11-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('player_id', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('competition', models.CharField(max_length=100)),
                ('home_team', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('goals', models.CharField(max_length=2)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.players')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.seasons')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
