# Generated by Django 3.2.9 on 2021-12-08 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20211130_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_to_scraping', models.CharField(max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.players')),
            ],
        ),
    ]
