# Generated by Django 3.2.9 on 2021-12-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_scraping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='player_id',
        ),
    ]
